# 리프트 모듈 설정
lift:
  min_h: 0.100
  max_h: 0.700
  initial_pose: 0.110
  usb_port: "/dev/ttyLM"
  baud_rate: 57600

# 헤드 모듈 설정 (다이나믹셀)
head:
  usb_port: "/dev/ttyHead"
  baud_rate: 115200

arm:
  robot_ip: "192.168.5.240"

tool:
  usb_port: "/dev/ttyGripper"
  baud_rate: 57600